### ISSUE TITLE
Transistor spec important, and needs a current limiting resistor in the base!

### ISSUE THREAD

**Issue by jimbojr** [raspberrypilearning/balloon-pi-tay-popper#2]
The base of the transistor is connected directly to a GPIO pin which is not good and may damage the Pi – basically it is just shorting the GPIO to GND via a diode, a current imiting resistor of 330R is needed.
 
Also the resource should mandate the type of transistor not merely suggest it as it needs to sink 750mA. The BC635 is fine as it can cope with 1A  but a lot of common SS variants will not – and may be destroyed in interesting ways (explode, overheat or catch on fire) which may be fun for the kids anyway but….

**Comment by RZRZR** [comment]
Thank you

**Comment by MarcScott** [comment]
@samalderhyde
Could you redo this image for me:
![original circuit](https://cloud.githubusercontent.com/assets/4516338/15936060/7a1a9810-2e61-11e6-8077-08ae499a4470.png)
so that the base of the transistor (the lowest leg on the diagram) connects to a 330ohm resistor (orange orange brown) and then that then connects to GPIO2, as shown below:
![citcuit](https://cloud.githubusercontent.com/assets/4516338/15935999/4a346a04-2e61-11e6-88ea-44f43523e071.png)
All other components can remain the same
